# Generated by Django 4.2.7 on 2024-01-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_from", models.CharField(default="USD", max_length=5)),
                ("currency_to", models.CharField(default="RUR", max_length=5)),
                ("exchange_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("rate_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "курс валют",
                "verbose_name_plural": "курсы валют",
            },
        ),
    ]
