# Generated by Django 4.2.7 on 2024-01-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="is_current_rate",
            field=models.BooleanField(default=False),
        ),
    ]
